# Generated by Django 2.2.16 on 2021-04-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='disabled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True, verbose_name='username'),
        ),
    ]
