# Generated by Django 2.0.4 on 2020-01-18 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="object_id",
        ),
    ]
