export default {
  general: {
    email: 'Email',
    thereWasAnError: 'There was an error processing your request.',
    password: 'Password',
    close: 'close',
    loading: 'Loading',
    okay: 'Okay',
    enterHere: 'Enter Here',
    next: 'Next',
    back: 'Back',
    home: 'Home',
    clearsummit: 'ClearSummit',
  },
  home: {
    greetings: 'Greetings',
    niceToSeeYou: (name: string) => `Nice to see you ${name}`,
    clickToReplaceName: 'Click to replace name',
  },
  login: {
    welcome: 'Welcome to ClearSummit',
    loginToSeeAmazingFeatures: 'Log in to your account to use our amazing features.',
    pleaseEnterAValid: 'Please enter a valid email address.',
    incorrectPassword: 'Incorrect password.',
    welcomeBack: 'Welcome Back',
    enterEmail: 'Enter Email Address',
    enterPassword: 'Enter Password',
    signIn: 'Log In',
    dontHaveAnAccount: "Don't Have An Account?",
    logout: 'Log Out',
  },
  signUp: {
    signUp: 'Sign Up',
    pleaseEnterAValidEmail: 'Please enter a valid email address.',
    passwordsDoNotMatch: 'Passwords do not match.',
    beAtLeast8: 'Be at least 8 characters',
    notExceed50: 'Not exceed 50 characters',
    containAtLeast1Number: 'Contain at least one number',
    containAtLeast1Special: 'Contain at least one special character',
    createAccount: 'Create Account',
    signUpToGet: 'Sign up to get started',
    passwordMustBe:
      'Password must be 8 characters and contain at least one letter, one number and one special character.',
    confirmPassword: 'Confirm Password',
    getStarted: 'Get Started!',
    inputEmail: 'Input Email Here',
    iAcceptThe: 'I accept the ',
    termsAndConditions: 'Terms and Conditions of Use.',
    firstName: 'First Name',
    lastName: 'Last Name',
    username: 'username',
  },
}
